"""added index

Revision ID: 3b87f7ce1f8d
Revises: 329a05d36b66
Create Date: 2025-04-06 18:40:44.219885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b87f7ce1f8d'
down_revision: Union[str, None] = '329a05d36b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('Contacts_birth_date_idx', 'contacts', ['birth_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Contacts_birth_date_idx', table_name='contacts')
    # ### end Alembic commands ###
